AWSTemplateFormatVersion: '2010-09-09'
Description: Car Listing Application - ECS Fargate

Parameters:
  DBHostParameter:
    Type: String
    Description: PostgreSQL Database Host
    NoEcho: true

  DBNameParameter:
    Type: String
    Description: PostgreSQL Database Name
    NoEcho: true

  DBUserParameter:
    Type: String
    Description: PostgreSQL Database User
    NoEcho: true

  DBPasswordParameter:
    Type: String
    Description: PostgreSQL Database Password
    NoEcho: true

  BackendImageUri:
    Type: String
    Description: Backend Docker Image URI from ECR Public
    Default: public.ecr.aws/c9g5y1u8/carswebapppublic:backend-ecs

  FrontendImageUri:
    Type: String
    Description: Frontend Docker Image URI from ECR Public
    Default: public.ecr.aws/c9g5y1u8/carswebapppublic:frontend-ecs

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for ECS and ALB

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets for ALB

  TaskSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for ECS tasks (public or private)

  AssignPublicIp:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Assign public IPs to tasks if using public subnets

  DesiredCount:
    Type: Number
    Default: 1
    MinValue: 1

  BackendContainerPort:
    Type: Number
    Default: 5001

  FrontendContainerPort:
    Type: Number
    Default: 80

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'car-listing-${AWS::StackName}'

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}/backend'
      RetentionInDays: 14

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}/frontend'
      RetentionInDays: 14

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref FrontendContainerPort
          ToPort: !Ref FrontendContainerPort
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: !Ref BackendContainerPort
          ToPort: !Ref BackendContainerPort
          SourceSecurityGroupId: !Ref ALBSecurityGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroup

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: !Ref BackendContainerPort
      TargetType: ip
      HealthCheckPath: /
      Matcher:
        HttpCode: '200-399'

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: !Ref FrontendContainerPort
      TargetType: ip
      HealthCheckPath: /
      Matcher:
        HttpCode: '200-399'

  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-backend'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Ref BackendImageUri
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
          Environment:
            - Name: PGHOST
              Value: !Ref DBHostParameter
            - Name: PGDATABASE
              Value: !Ref DBNameParameter
            - Name: PGUSER
              Value: !Ref DBUserParameter
            - Name: PGPASSWORD
              Value: !Ref DBPasswordParameter
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-frontend'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Ref FrontendImageUri
          PortMappings:
            - ContainerPort: !Ref FrontendContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  BackendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      ServiceName: !Sub '${AWS::StackName}-backend'
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: !Ref AssignPublicIp
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets: !Ref TaskSubnets
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: !Ref BackendContainerPort
          TargetGroupArn: !Ref BackendTargetGroup

  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      ServiceName: !Sub '${AWS::StackName}-frontend'
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref FrontendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: !Ref AssignPublicIp
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets: !Ref TaskSubnets
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: !Ref FrontendContainerPort
          TargetGroupArn: !Ref FrontendTargetGroup

Outputs:
  LoadBalancerDNS:
    Description: Public ALB DNS name
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  ApplicationURL:
    Description: Application URL
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'
