AWSTemplateFormatVersion: '2010-09-09'
Description: Car Listing Application - ECS Fargate with Proper Networking

Parameters:
  DBHostParameter:
    Type: String
    Description: PostgreSQL Database Host
    NoEcho: true

  DBNameParameter:
    Type: String
    Description: PostgreSQL Database Name
    NoEcho: true

  DBUserParameter:
    Type: String
    Description: PostgreSQL Database User
    NoEcho: true

  DBPasswordParameter:
    Type: String
    Description: PostgreSQL Database Password
    NoEcho: true

  DBSecurityGroupId:
    Type: String
    Description: RDS Security Group ID (for proper ingress rules)

  BackendImageUri:
    Type: String
    Description: Backend Docker Image URI from ECR Public
    Default: public.ecr.aws/c9g5y1u8/carswebapppublic:backend-dev

  FrontendImageUri:
    Type: String
    Description: Frontend Docker Image URI from ECR Public
    Default: public.ecr.aws/c9g5y1u8/carswebapppublic:frontend-dev

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for ECS and ALB

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets for ALB

  TaskSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for ECS tasks

  # Optional: ARN of an ACM certificate to enable HTTPS on the ALB. If empty, ALB will only use HTTP.
  ACMCertificateArn:
    Type: String
    Description: ARN of an ACM certificate to enable HTTPS on the ALB (leave empty to skip HTTPS)
    Default: ''

  # Optional Google Geocoding API key (server-side geocoding)
  GoogleGeocoderKey:
    Type: String
    Description: (Optional) Google Geocoding API Key to enable server-side address lookup. Use secrets for production.
    Default: ''
    NoEcho: true

  # Optional: Secrets Manager ARN containing DB password (JSON or plaintext). If provided, it will be injected as PGPASSWORD.
  DBPasswordSecretArn:
    Type: String
    Description: ARN of a Secrets Manager secret that contains the DB password (optional)
    Default: ''
    NoEcho: true

  AllowedClientIP:
    Type: String
    Description: Your public IP address for ALB access (e.g., 172.99.221.5/32)
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}(/\d{1,2})?$'

  DesiredCount:
    Type: Number
    Default: 1
    MinValue: 1

Conditions:
  CreateHttps: !Not [ !Equals [ !Ref ACMCertificateArn, '' ] ]
  HasDBPasswordSecret: !Not [ !Equals [ !Ref DBPasswordSecretArn, '' ] ]


  # DesiredCount is a parameter, moved down to Parameters section
  # (Was previously misdeclared here)


Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  # IAM Roles
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECSTaskLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/*'

  # Optional policy to allow the task to retrieve DB password from Secrets Manager
  TaskExecutionSecretAccess:
    Condition: HasDBPasswordSecret
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWS::StackName}-secret-access'
      Roles:
        - !Ref TaskExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref DBPasswordSecretArn
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: '*'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  # CloudWatch Logs
  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}/backend'
      RetentionInDays: 7

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}/frontend'
      RetentionInDays: 7

  # Security Groups - PROPERLY SEPARATED
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowedClientIP
          Description: Allow HTTP from specified IP address
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-alb-sg'

  ECSTaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5001
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Backend from ALB
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Frontend from ALB
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ecs-sg'

  # Allow RDS to receive traffic from ECS tasks
  RDSIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBSecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref ECSTaskSecurityGroup
      Description: PostgreSQL access from ECS tasks

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroup

  # HTTP listener (will be used for redirects to HTTPS when an ACM certificate ARN is provided)
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  # Redirect rule that sends all HTTP traffic to HTTPS when an ACM cert is provided
  HttpRedirectRule:
    Condition: CreateHttps
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301
            Host: '#{host}'
            Path: '#{path}'
            Query: '#{query}'

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 5001
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200-399'

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200-399'

  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  # HTTPS listener (created only when an ACM certificate ARN is provided)
  HttpsListener:
    Condition: CreateHttps
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ACMCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  # HTTPS rule to route /api/* to backend when using HTTPS
  ApiListenerRuleHttps:
    Condition: CreateHttps
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpsListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-backend'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Ref BackendImageUri
          PortMappings:
            - ContainerPort: 5001
          Environment:
            Fn::If:
              - HasDBPasswordSecret
              - - Name: PGHOST
                  Value: !Ref DBHostParameter
                - Name: PGPORT
                  Value: '5432'
                - Name: PGDATABASE
                  Value: !Ref DBNameParameter
                - Name: PGUSER
                  Value: !Ref DBUserParameter
                - Name: PORT
                  Value: '5001'
                - Name: GOOGLE_GEOCODER_KEY
                  Value: !Ref GoogleGeocoderKey
                - Name: PGSSLROOTCERT
                  Value: '/app/certs/rds-global-bundle.pem'
                - Name: PGSSLVERIFY
                  Value: 'false'
              - - Name: PGHOST
                  Value: !Ref DBHostParameter
                - Name: PGPORT
                  Value: '5432'
                - Name: PGDATABASE
                  Value: !Ref DBNameParameter
                - Name: PGUSER
                  Value: !Ref DBUserParameter
                - Name: PGPASSWORD
                  Value: !Ref DBPasswordParameter
                - Name: PORT
                  Value: '5001'
                - Name: GOOGLE_GEOCODER_KEY
                  Value: !Ref GoogleGeocoderKey
                - Name: PGSSLROOTCERT
                  Value: '/app/certs/rds-global-bundle.pem'
                - Name: PGSSLVERIFY
                  Value: 'false'

          Secrets:
            Fn::If:
              - HasDBPasswordSecret
              - - Name: PGPASSWORD
                  ValueFrom: !Ref DBPasswordSecretArn
              - !Ref 'AWS::NoValue'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-frontend'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Ref FrontendImageUri
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: frontend

  BackendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      ServiceName: !Sub '${AWS::StackName}-backend'
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSTaskSecurityGroup
          Subnets: !Ref TaskSubnets
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 5001
          TargetGroupArn: !Ref BackendTargetGroup

  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      ServiceName: !Sub '${AWS::StackName}-frontend'
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref FrontendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSTaskSecurityGroup
          Subnets: !Ref TaskSubnets
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 80
          TargetGroupArn: !Ref FrontendTargetGroup

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster

  ALBDNSName:
    Description: Application Load Balancer DNS
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  ApplicationURL:
    Description: Application URL
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'

  ECSSecurityGroupId:
    Description: ECS Task Security Group ID
    Value: !Ref ECSTaskSecurityGroup

  BackendServiceName:
    Description: Backend ECS Service Name
    Value: !GetAtt BackendService.Name

  FrontendServiceName:
    Description: Frontend ECS Service Name
    Value: !GetAtt FrontendService.Name

  BackendLogGroup:
    Description: Backend CloudWatch Log Group
    Value: !Ref BackendLogGroup

  FrontendLogGroup:
    Description: Frontend CloudWatch Log Group
    Value: !Ref FrontendLogGroup
